version: '3.9'
services:
    postgres-docker:
      image: postgreslocal
      ports:
        - 5433:5432
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=p@stgress
        - POSTGRES_DB=postgres
      volumes:
        - ./data:/var/lib/postgresql/data
        - ./load-extensions.sh:/docker-entrypoint-initdb.d/load-extensions.sh
        # - ./postgresql.conf:/var/lib/postgresql/data
      container_name: postgres-docker